spring:
  kafka:
    bootstrap-servers: 42.193.22.180:9092,42.193.22.180:9093,42.193.22.180:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-group
      enable-auto-commit: true
      auto-commit-interval: 1000
      properties:
        security.protocol: PLAINTEXT
        request.timeout.ms: 60000
    listener:
      type: batch
    properties:
      kafka:
        version: 3.4.1
      max.poll.records: 100
      concurrency: 3
